"""
📚 Investment Quotes & Wisdom
============================

A comprehensive collection of investment quotes, facts, and wisdom
from the user's quotes.txt file. Used to keep users engaged during analysis.
"""

FINANCIAL_FACTS = [
    # 📊 ACTUAL INVESTMENT FACTS (25)
    "Time in the market beats timing the market.",
    "90% of traders lose money in their first year.",
    "Compounding is the 8th wonder of the world – if you're patient.",
    "The stock market has always recovered after every crash in history.",
    "Diversification reduces risk but may also limit returns.",
    "Inflation silently eats your money if you don't invest.",
    "Warren Buffett made 99% of his wealth after the age of 50.",
    "The average annual return of the S&P 500 is around 10%.",
    "Long-term investors usually beat short-term traders.",
    "High returns often come with high risks.",
    "Bear markets are temporary. Bull markets last longer.",
    "Passive index investing often beats most active funds.",
    "The earlier you invest, the more you benefit from compounding.",
    "Overtrading kills returns more than bad stock picks.",
    "Most millionaires invest regularly, not occasionally.",
    "Missing the 10 best days in the market can cut your returns in half.",
    "Real estate and stocks are the top two long-term wealth builders.",
    "Bitcoin's total supply is capped at 21 million – scarcity drives demand.",
    "Inflation is why saving alone doesn't make you rich.",
    "The market doesn't care about your emotions.",
    "More information doesn't always lead to better decisions.",
    "Penny stocks rarely make you rich – they usually make you broke.",
    "Timing the top or bottom is almost impossible – consistency wins.",
    "In investing, 'doing nothing' is often the best move.",
    "Debt can build wealth, but also destroy it faster.",
    
    # 🤔 FUN & WEIRD FACTS (25)
    "If you invested $1,000 in Apple in 2003, it'd be over $400,000 today.",
    "There's a 'Fear Index' in the market called the VIX.",
    "One tweet from Elon Musk can move billions in value.",
    "The first stock exchange started in a coffee house.",
    "Dutch tulip bulbs once cost more than houses.",
    "Jeff Bezos became a billionaire thanks to books, not rockets.",
    "Some investors buy stocks based on astrology. Yes, really.",
    "One man traded a red paperclip for a house in 14 trades.",
    "Warren Buffett still uses a flip phone.",
    "A monkey picking random stocks once outperformed fund managers.",
    "2021 saw Dogecoin rise over 12,000% – it started as a joke.",
    "There's an actual 'Toilet Paper Index' in economic humor.",
    "Some ETFs track things like pot, video games, and even obesity.",
    "The term 'bull' comes from how a bull thrusts upward.",
    "The Great Depression caused some people to hide cash in walls.",
    "The 2008 crash started with home loans and ended in global panic.",
    "Mark Cuban bought a private jet online in one click.",
    "There's a stock market just for racehorses (yes, really).",
    "'Sell in May and go away' is an actual Wall Street saying.",
    "The 'Lipstick Index' suggests makeup sales rise in recessions.",
    "In Japan, investors once bowed to the stock exchange screen.",
    "Some people use AI bots to trade their entire portfolio.",
    "Amazon was once just a bookstore with losses.",
    "Stocks are emotional. They go up on hope and fall on fear.",
    "Gamers once caused GameStop to jump 1,500% in days.",
    
    # 😏 SARCASTIC INVESTMENT TRUTHS (30)
    "'Buy high, sell low' – said every panicked investor ever.",
    "Risk only seems fun until you actually lose money.",
    "Everyone's a genius in a bull market.",
    "The market doesn't care about your horoscope.",
    "Your gut feeling is not a reliable investment strategy.",
    "Most trading courses are just expensive ways to feel smart.",
    "The quickest way to double your money? Fold it and put it back.",
    "If your taxi driver gives you stock tips, it's probably time to sell.",
    "A 'sure thing' in the market is just another name for a trap.",
    "HODL is not a strategy – it's a cry for help.",
    "'It's different this time' – last words before every crash.",
    "Don't worry, that one stock *will* recover... eventually... maybe.",
    "If you feel like a genius, it's time to take profits.",
    "Paper profits are just fancy dreams.",
    "The more complex your strategy, the faster it fails.",
    "No one brags about their losses on social media.",
    "Buying because of FOMO is a tax on impatience.",
    "Leverage is like a sword – looks cool, until it cuts you.",
    "Your best friend isn't a financial advisor (probably).",
    "Red days are nature's way of reminding you to breathe.",
    "Every dip feels like the end. It's not.",
    "'This stock can't fall anymore!' – it does.",
    "10% returns are boring – until you compare them over 20 years.",
    "Panic selling is the most expensive emotional reaction.",
    "The market gives – and takes faster than your ex.",
    "If it feels too easy, you're missing something.",
    "That stock you sold? It just doubled.",
    "Technical analysis: draw some lines and hope they listen.",
    "Most 'breakouts' are just fakeouts in disguise.",
    "'Investing is easy' – said no experienced investor ever.",
    
    # 💬 FAMOUS INVESTOR QUOTES (40)
    "'Be fearful when others are greedy, and greedy when others are fearful.' – Warren Buffett",
    "'The stock market is a device for transferring money from the impatient to the patient.' – Warren Buffett",
    "'Risk comes from not knowing what you're doing.' – Warren Buffett",
    "'Know what you own, and know why you own it.' – Peter Lynch",
    "'The four most dangerous words in investing are: This time it's different.' – Sir John Templeton",
    "'In investing, what is comfortable is rarely profitable.' – Robert Arnott",
    "'Buy when there's blood in the streets.' – Baron Rothschild",
    "'It's not whether you're right or wrong. It's how much you make when you're right and how much you lose when you're wrong.' – George Soros",
    "'I made a fortune by selling too early.' – Bernard Baruch",
    "'Markets can remain irrational longer than you can remain solvent.' – John Maynard Keynes",
    "'An investment in knowledge pays the best interest.' – Benjamin Franklin",
    "'Don't look for the needle in the haystack. Just buy the haystack!' – John C. Bogle",
    "'Wide diversification is only required when investors do not understand what they are doing.' – Warren Buffett",
    "'The goal of a successful investor is to make a lot of money slowly.' – Bill Gross",
    "'You make most of your money in a bear market, you just don't realize it at the time.' – Shelby Davis",
    "'Cut your losses short. Let your winners run.' – Jesse Livermore",
    "'It is not the strongest or most intelligent who survive, but those who can best manage change.' – Charles Darwin (applied to investing)",
    "'Only when the tide goes out do you discover who's been swimming naked.' – Warren Buffett",
    "'If you don't find a way to make money while you sleep, you will work until you die.' – Warren Buffett",
    "'People who succeed in the stock market also accept periodic losses, setbacks, and unexpected occurrences.' – Peter Lynch",
    "'The individual investor should act consistently as an investor and not as a speculator.' – Benjamin Graham",
    "'You don't have to be smarter than the rest. You have to be more disciplined.' – Warren Buffett",
    "'In the short run, the market is a voting machine, but in the long run, it is a weighing machine.' – Benjamin Graham",
    "'Fear incites human action far more urgently than does the impressive weight of historical evidence.' – Jeremy Siegel",
    "'The trend is your friend until it ends.' – Ed Seykota",
    "'Never invest in a business you cannot understand.' – Warren Buffett",
    "'Cash combined with courage in a time of crisis is priceless.' – Warren Buffett",
    "'Price is what you pay. Value is what you get.' – Warren Buffett",
    "'Good investing is boring.' – George Soros",
    "'Success in investing doesn't correlate with IQ… what you need is the temperament.' – Warren Buffett",
    "'To be a successful investor, you must divorce yourself from the fears and greed of the people around you.' – Warren Buffett",
    "'Patience is the most underrated investing skill.' – Howard Marks",
    "'Volatility is not risk. Risk is losing money.' – Charlie Munger",
    "'The desire to perform all the time is usually a barrier to good performance over time.' – Robert Olstein",
    "'The stock market is filled with individuals who know the price of everything, but the value of nothing.' – Philip Fisher",
    "'You get recessions. You have stock market declines. If you don't understand that's going to happen, then you're not ready.' – Peter Lynch",
    "'The market always climbs a wall of worry.' – Old Wall Street saying",
    "'Do not save what is left after spending, but spend what is left after saving.' – Warren Buffett",
    "'Liquidity is like oxygen. You don't notice it until it's gone.' – Warren Buffett",
    "'You only have to do a few things right in your life so long as you don't do too many things wrong.' – Warren Buffett"
]

def get_random_fact():
    """Get a random investment quote from the collection"""
    import random
    return random.choice(FINANCIAL_FACTS)

def get_facts_count():
    """Get the total number of quotes available"""
    return len(FINANCIAL_FACTS) 